{{- if and .Values.prometheus.javaagent.enabled .Values.prometheus.podmonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name:  {{ include "xwiki.fullname" . }}
  labels:
    {{- include "xwiki.labels" . | nindent 4 }}
    {{- with .Values.prometheus.podmonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "xwiki.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
      - targetPort: {{ .Values.prometheus.javaagent.port }}
{{- end }}
