apiVersion: v1
kind: Service
metadata:
  name:  {{ include "xwiki.fullname" . }}
  labels:
    {{- include "xwiki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if gt (len .Values.service.externalIPs) 0 }}
  externalIPs:
    {{- range .Values.service.externalIPs }}
    - {{ . }}
    {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  {{- if .Values.prometheus.javaagent.enabled }}
    - port: {{ .Values.prometheus.javaagent.port }}
      targetPort: {{ .Values.prometheus.javaagent.port }}
      protocol: TCP
      name: monitoring
  {{- end }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  selector:
    {{- include "xwiki.selectorLabels" . | nindent 4 }}
